# Generated by Django 3.0.8 on 2020-07-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_related_links_html', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_text', models.CharField(default='NONE', max_length=128)),
                ('html_path', models.CharField(max_length=256)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ContentTable')),
            ],
        ),
    ]
