# Generated by Django 3.0.8 on 2020-07-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contenttable_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='html_path',
            new_name='url_additum',
        ),
    ]
